import { json2csv } from 'json-2-csv';

/**
 * Generate a branded TXT file content
 * @param {Array} tracks - List of track objects
 * @param {String} planType - 'free', 'starter', 'creator'
 */
export const generateTXT = (tracks, planType) => {
  let content = '';
  const isPremium = planType === 'creator';

  // Header (Branding for non-creator)
  if (!isPremium) {
    content += '--------------------------------------------------\n';
    content += '   Generated via Linkiz.com Playlist Manager\n';
    content += '--------------------------------------------------\n\n';
  }

  // Content
  tracks.forEach((track, index) => {
    content += `${index + 1}. ${track.artist} - ${track.title} [${track.duration}]\n`;
    content += `   Original: ${track.url}\n`;
    // Add smart links if needed, or keep txt simple
    content += '\n';
  });

  // Footer (Upsell for non-creator)
  if (!isPremium) {
    content += '\n--------------------------------------------------\n';
    content += '  Upgrade to Linkiz Creator for Clean Exports\n';
    content += '  https://linkiz.com/pricing\n';
    content += '--------------------------------------------------\n';
  }

  return content;
};

/**
 * Generate a branded CSV file content
 * @param {Array} tracks - List of track objects
 * @param {String} planType - 'free', 'starter', 'creator'
 */
export const generateCSV = async (tracks, planType) => {
  const isPremium = planType === 'creator';
  
  // Define columns
  const keys = [
    { field: 'artist', title: 'Artist' },
    { field: 'title', title: 'Title' },
    { field: 'duration', title: 'Duration' },
    { field: 'platform', title: 'Source Platform' },
    { field: 'url', title: 'Original URL' }
  ];

  // Generate CSV string
  let csv = await json2csv(tracks, { keys });

  // Add Header/Footer Branding by appending raw text rows
  // Note: This makes the CSV "technically" invalid for some strict parsers, 
  // but works fine for Excel/human reading which is the target.
  // If strict CSV is needed, we should only append to Comments or specific columns.
  
  if (!isPremium) {
    const header = '# Generated by Linkiz.com\n';
    const footer = '\n# Upgrade to Creator for clean exports at linkiz.com';
    return header + csv + footer;
  }

  return csv;
};
