#!/usr/bin/env node

/**
 * Cookie Validation Test Script
 *
 * Tests if the current cookies.json file contains valid YouTube cookies
 * by making a test request using yt-dlp.
 *
 * Exit codes:
 *   0 - Cookies are valid and working
 *   1 - Cookies are invalid, missing, or not working
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

// Get current directory
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.join(__dirname, '..');

// Configuration paths
const COOKIES_JSON_PATH = path.join(ROOT_DIR, 'cookies.json');
const COOKIES_TXT_PATH = path.join(ROOT_DIR, 'cookies.txt');

// Essential YouTube cookies
const ESSENTIAL_COOKIES = ['SID', 'HSID', 'SSID', 'APISID', 'SAPISID', 'LOGIN_INFO'];

// Test YouTube video URL (a short, always-available video)
// const TEST_VIDEO_URL = 'https://www.youtube.com/watch?v=jNQXAC9IVRw'; // "Me at the zoo" - first YouTube video
const TEST_VIDEO_URL = "https://youtu.be/HECUlWMPQPk?si=RQjRbi1w_Aj5Y4Pm"; // "Me at the zoo" - first YouTube video

/**
 * Get formatted timestamp
 */
function getTimestamp() {
  return new Date().toISOString().replace('T', ' ').substring(0, 19);
}

/**
 * Log with timestamp
 */
function log(message, type = 'INFO') {
  const prefix = {
    'INFO': '',
    'WARN': '\u26a0\ufe0f ',
    'ERROR': '\u274c ',
    'SUCCESS': '\u2705 ',
    'TEST': '\ud83e\uddea '
  };
  console.log(`[${getTimestamp()}] ${prefix[type] || ''}${message}`);
}

/**
 * Convert JSON cookies to Netscape format
 */
function jsonToNetscape(jsonCookies) {
  let netscape = '# Netscape HTTP Cookie File\n# This file is generated by the application. Do not edit.\n\n';

  jsonCookies.forEach(cookie => {
    const domain = cookie.domain.startsWith('.') ? cookie.domain : `.${cookie.domain}`;
    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const cookiePath = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiration = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;

    netscape += `${domain}\t${includeSubdomains}\t${cookiePath}\t${secure}\t${expiration}\t${cookie.name}\t${cookie.value}\n`;
  });

  return netscape;
}

/**
 * Check if cookies.json exists and contains valid structure
 */
function checkCookiesFile() {
  log('Checking cookies.json file...', 'TEST');

  if (!fs.existsSync(COOKIES_JSON_PATH)) {
    log(`cookies.json not found at: ${COOKIES_JSON_PATH}`, 'ERROR');
    return null;
  }

  try {
    const content = fs.readFileSync(COOKIES_JSON_PATH, 'utf8');
    const cookies = JSON.parse(content);

    if (!Array.isArray(cookies)) {
      log('cookies.json does not contain an array', 'ERROR');
      return null;
    }

    if (cookies.length === 0) {
      log('cookies.json is empty', 'ERROR');
      return null;
    }

    log(`Found ${cookies.length} cookies in file`, 'INFO');
    return cookies;
  } catch (error) {
    log(`Failed to parse cookies.json: ${error.message}`, 'ERROR');
    return null;
  }
}

/**
 * Check for essential YouTube cookies
 */
function checkEssentialCookies(cookies) {
  log('Checking for essential YouTube cookies...', 'TEST');

  const cookieNames = cookies.map(c => c.name);
  const found = [];
  const missing = [];

  ESSENTIAL_COOKIES.forEach(name => {
    if (cookieNames.includes(name)) {
      const cookie = cookies.find(c => c.name === name);
      if (cookie && cookie.value) {
        found.push(name);
      } else {
        missing.push(`${name} (empty value)`);
      }
    } else {
      missing.push(name);
    }
  });

  log(`Essential cookies found: ${found.length}/${ESSENTIAL_COOKIES.length}`, 'INFO');

  if (found.length > 0) {
    log(`Present: ${found.join(', ')}`, 'INFO');
  }

  if (missing.length > 0) {
    log(`Missing: ${missing.join(', ')}`, 'WARN');
  }

  // Consider valid if at least 4 essential cookies are present
  return found.length >= 4;
}

/**
 * Check cookie expiration dates
 */
function checkCookieExpiration(cookies) {
  log('Checking cookie expiration dates...', 'TEST');

  const now = Math.floor(Date.now() / 1000);
  const expired = [];
  const valid = [];
  const noExpiry = [];

  cookies.forEach(cookie => {
    if (ESSENTIAL_COOKIES.includes(cookie.name)) {
      if (!cookie.expirationDate || cookie.expirationDate === 0) {
        noExpiry.push(cookie.name);
      } else if (cookie.expirationDate < now) {
        expired.push(cookie.name);
      } else {
        const daysLeft = Math.floor((cookie.expirationDate - now) / 86400);
        valid.push(`${cookie.name} (${daysLeft} days left)`);
      }
    }
  });

  if (expired.length > 0) {
    log(`Expired cookies: ${expired.join(', ')}`, 'WARN');
  }

  if (valid.length > 0) {
    log(`Valid cookies: ${valid.join(', ')}`, 'INFO');
  }

  if (noExpiry.length > 0) {
    log(`Session cookies (no expiry): ${noExpiry.join(', ')}`, 'INFO');
  }

  // Fail if any essential cookies are expired
  return expired.length === 0;
}

/**
 * Generate cookies.txt from cookies.json
 */
function generateCookiesTxt(cookies) {
  log('Generating cookies.txt for yt-dlp...', 'TEST');

  try {
    const netscapeContent = jsonToNetscape(cookies);
    fs.writeFileSync(COOKIES_TXT_PATH, netscapeContent);
    log(`cookies.txt generated: ${COOKIES_TXT_PATH}`, 'SUCCESS');
    return true;
  } catch (error) {
    log(`Failed to generate cookies.txt: ${error.message}`, 'ERROR');
    return false;
  }
}

/**
 * Test cookies with yt-dlp
 */
async function testWithYtDlp() {
  log('Testing cookies with yt-dlp...', 'TEST');

  try {
    // First check if yt-dlp is available
    try {
      await execAsync('yt-dlp --version');
    } catch (e) {
      log('yt-dlp not found in PATH, skipping live test', 'WARN');
      log('Install yt-dlp to enable live cookie testing', 'INFO');
      return true; // Don't fail if yt-dlp is not installed
    }

    // Test getting video info with cookies
    const command = `yt-dlp --cookies "${COOKIES_TXT_PATH}" --dump-single-json --no-warnings "${TEST_VIDEO_URL}"`;

    log(`Running: yt-dlp --cookies cookies.txt --dump-single-json "${TEST_VIDEO_URL}"`, 'INFO');

    const { stdout, stderr } = await execAsync(command, {
      timeout: 60000,
      maxBuffer: 1024 * 1024 * 10
    });

    const videoInfo = JSON.parse(stdout);

    if (videoInfo && videoInfo.title) {
      log(`Successfully fetched video info: "${videoInfo.title}"`, 'SUCCESS');

      // Check if we're authenticated by looking for age-restricted content access
      // or subscription-only content availability
      if (videoInfo.channel) {
        log(`Channel: ${videoInfo.channel}`, 'INFO');
      }

      return true;
    } else {
      log('yt-dlp returned empty or invalid response', 'WARN');
      return false;
    }

  } catch (error) {
    const errorMessage = error.stderr || error.message || error.toString();

    // Check for specific error types
    if (errorMessage.includes('bot') || errorMessage.includes('Sign in to confirm')) {
      log('YouTube bot detection triggered - cookies may be invalid', 'ERROR');
      return false;
    }

    if (errorMessage.includes('cookies') || errorMessage.includes('login')) {
      log(`Cookie-related error: ${errorMessage}`, 'ERROR');
      return false;
    }

    // Network or other transient errors
    log(`yt-dlp test error: ${errorMessage.substring(0, 200)}`, 'WARN');
    log('This may be a network issue, not necessarily invalid cookies', 'INFO');
    return true; // Don't fail on network issues
  }
}

/**
 * Main test function
 */
async function runTests() {
  console.log('');
  log('='.repeat(60), 'INFO');
  log('YouTube Cookie Validation Test', 'INFO');
  log('='.repeat(60), 'INFO');
  console.log('');

  let allPassed = true;

  // Test 1: Check cookies.json file
  const cookies = checkCookiesFile();
  if (!cookies) {
    log('TEST FAILED: cookies.json file check', 'ERROR');
    allPassed = false;
  } else {
    log('TEST PASSED: cookies.json file exists and is valid JSON', 'SUCCESS');
  }

  console.log('');

  // Test 2: Check essential cookies (only if file exists)
  if (cookies) {
    const hasEssential = checkEssentialCookies(cookies);
    if (!hasEssential) {
      log('TEST FAILED: Essential cookies check', 'ERROR');
      allPassed = false;
    } else {
      log('TEST PASSED: Essential cookies present', 'SUCCESS');
    }

    console.log('');

    // Test 3: Check expiration
    const notExpired = checkCookieExpiration(cookies);
    if (!notExpired) {
      log('TEST FAILED: Cookie expiration check', 'ERROR');
      allPassed = false;
    } else {
      log('TEST PASSED: Cookies not expired', 'SUCCESS');
    }

    console.log('');

    // Test 4: Generate cookies.txt
    const txtGenerated = generateCookiesTxt(cookies);
    if (!txtGenerated) {
      log('TEST FAILED: cookies.txt generation', 'ERROR');
      allPassed = false;
    } else {
      log('TEST PASSED: cookies.txt generated', 'SUCCESS');
    }

    console.log('');

    // Test 5: Live test with yt-dlp
    const ytdlpWorks = await testWithYtDlp();
    if (!ytdlpWorks) {
      log('TEST FAILED: yt-dlp live test', 'ERROR');
      allPassed = false;
    } else {
      log('TEST PASSED: yt-dlp live test', 'SUCCESS');
    }
  }

  console.log('');
  log('='.repeat(60), 'INFO');

  if (allPassed) {
    log('ALL TESTS PASSED - Cookies are valid!', 'SUCCESS');
    log('='.repeat(60), 'INFO');
    process.exit(0);
  } else {
    log('SOME TESTS FAILED - Cookies may need refresh', 'ERROR');
    log('Run: node scripts/refresh-cookies.js', 'INFO');
    log('='.repeat(60), 'INFO');
    process.exit(1);
  }
}

// Run tests
runTests().catch(error => {
  log(`Fatal error: ${error.message}`, 'ERROR');
  process.exit(1);
});
